version: '3'
services:
  jaeger:
    image: jaegertracing/all-in-one:1.8
    network_mode: 'host' 
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
  mongodb:
    image: mongo
    network_mode: 'host' 
    ports:
      - "27017:27017"
    volumes:
      - 'mongodata:/data/db'
  yase-core:
    image: yase-core
    network_mode: "host"
    ports:
      - "9000:9000"
    environment:
      - YASE_STORAGE_SERVICE_HOST=localhost
      - YASE_STORAGE_SERVICE_PORT=9001
  yase-storage:
    image: yase-storage
    network_mode: "host"
    ports:
      - "9001:9001"
  yase-ui:
    image: yase-ui
    ports:
      - '8080:3000'
    environment:
      - NODE_ENV=development
      - YASE_CORE_SERVICE_HOST=localhost
      - YASE_CORE_SERVICE_PORT=9000

volumes:
   mongodata:
   

