version: '3'
services:
  mongodb:
    image: mongo
    network_mode: 'host'
    ports:
      - "27017:27017"
    volumes:
      - 'mongodata:/data/db'
  yase-core:
    image: francomelandri/yase-core
    network_mode: "host"
    ports:
      - "9000:9000"
    environment:
      - YASE_STORAGE_SERVICE_HOST=localhost
      - YASE_STORAGE_SERVICE_PORT=9001
  yase-storage:
    image: francomelandri/yase-storage
    network_mode: "host"
    ports:
      - "9001:9001"
  yase-ui:
    image: francomelandri/yase-ui
    ports:
      - '8080:3000'
    environment:
      - NODE_ENV=development
      - YASE_CORE_SERVICE_HOST=localhost
      - YASE_CORE_SERVICE_PORT=9000

volumes:
   mongodata:
   

