version: '3'
services:
  mongodb:
    image: mongo
   # network_mode: 'host'
    ports:
      - "27017:27017"
    volumes:
      - 'mongodata:/data/db'
  # yase-core:
  #   image: yase-core
  #   network_mode: "host"
  #   ports:
  #     - "9000:9000"
  # yase-storage:
  #   image: yase-storage
  #   network_mode: "host"
  #   ports:
  #     - "9001:9001"
  # yase-ui:
  #   image: yase-ui
  #   volumes:
  #     - '../yase-ui/:/usr/src/app'
  #     - '/usr/src/app/node_modules'
  #   ports:
  #     - '8080:3000'
  #   environment:
  #     - NODE_ENV=development

volumes:
   mongodata:
   

