apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: yase-ui
  name: yase-ui
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: yase-ui
    spec:
      containers:
      - env:
        - name: NODE_ENV
          value: development
        image: francomelandri/yase-ui
        name: yase-ui
        ports:
        - containerPort: 3000
        resources: {}
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: yase-ui
  name: yase-ui
spec:
  type: NodePort
  ports:
  - name: "8080"
    port: 8080
    targetPort: 3000
    nodePort: 30002
  selector:
    io.kompose.service: yase-ui
status:
  loadBalancer: {}
